CREATE TABLE BOOK (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(256) NOT NULL,
  ISBN VARCHAR(20) NOT NULL,
  AUTHOR VARCHAR(128) NOT NULL
);

CREATE TABLE PERSON (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(128) NOT NULL,
  PHONE VARCHAR(30),
  EMAIL_ADDRESS VARCHAR(128) NOT NULL
);

CREATE TABLE PERSON_BOOKS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  PERSON_ID INT NOT NULL,
  BOOK_ID INT NOT NULL,
  FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID),
  FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID)
);